name: Java CI - Run Tests Before Merge

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (Adoptium)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptium'

    - name: Compile Java code
      run: |
        javac -d out src/loginapp/loginapp.java src/test/loginApptest.java

    - name: Run JUnit tests
      run: |
        java -cp out org.junit.runner.JUnitCore loginApptest
