name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # Specify your Java version here

    - name: Compile Java code
      run: |
        mkdir -p out
        javac -d out src/**/*.java # Adjust the path to your source files as needed

    - name: Run Java application
      run: |
        java -cp out MainClassName # Replace MainClassName with the name of your main class
