name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 (Adoptium)
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptium'

    - name: Build with IntelliJ
      run: |
        java -version
        javac -d out src/loginapp/loginapp.java src/test/loginApptest.java

    - name: Run tests with JUnit
      run: |
        java -cp out org.junit.runner.JUnitCore loginApptest
